---
title: "大数据分析师系列课程大纲"
date: "`r Sys.Date()`"
author: 汤银才
output:
  rmdformats::readthedown:
#    code_folding: hide
    self_contained: true
    thumbnails: false
    lightbox: false
    toc_depth: 2
#    number_sections: true    
    toc_float:
      collapsed: true
      smooth_scroll: true    
---


```{r knitr_init, echo=FALSE, results="asis", cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print = "75")
opts_chunk$set(echo = FALSE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = FALSE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
opts_knit$set(width = 75)
```

# _Series I/基础系列_

## A-1. 大数据行业前瞻(导论)

**课程性质**: 大数据分析基础系列

**大纲制定**: 汤银才

**课件开发**: 倪中新

**建议学时**: 2/周 授课，共10周，共20小时

### 课程介绍

- 2012年以来，由于互联网和信息行业的快速发展，大数据越来越引起人们的关注，已经引发自云计算、互联网之后IT行业的又一大颠覆性技术革命。人们用大数据来描述和定义信息爆炸时代产生的海量数据，并命名与之相关的技术发展与创新。面对信息的激流、多元化数据的涌现，大数据已经为个人生活、企业经营，甚至国家与社会的发展都带来了机遇和挑战，大数据已经成为IT信息产业中最具潜力的蓝海。 

- 本课程旨在系统、全面地介绍了关于大数据技术与应用的基本知识和技能，详细介绍了大数据与大数据时代、大数据的可视化、大数据的商业规则、大数据时代的思维变革、大数据促进医疗与健康、大数据激发创造力、大数据预测分析、支撑大数据的技术、数据科学与数据科学家和大数据的未来等内容。

- 本课程是大数据分析的基础课程，学员可以通过学习全面地了解和熟悉大数据理念、基础知识、相关技术、行业应用及数据科学家成长之路，使学生对未来的课程产生浓厚的学习热情，提高学习兴趣，较早地确定自己未来的发展路径。

### 课程目标

本课程旨在培养学生/学员

- 了解大数据与数据科学中的基本概念

- 熟悉大数据分析需要的基本知识和技能

- 了解大数据商业价值与行业动态

- 了解大数据人才市场现状与不同层次人才的准入门槛

### 适合学生/学员：  

- 统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，企业高层管理者，数据业务主管，......

### 课程大纲

1. 数据与大数据时代

    -	大数据概念

    -	大数据思维

    -	大数据与BI

    -	大数据分析与云计算

2. 大数据行业动态

    -	大数据国家战略

    -	谷歌的大数据行动

    -	亚马逊的大数据行动

    -	信息成为一种竞争优势

    -	大数据营销

3. 大数据时代的思维变革

    -	大数据大挑战

    -	数据科学与大数据建模

    - 大数据统计思维

    - 大数据贝叶斯思维

    - 大数据预测思维

4. 大数据分析行业应用实践

    -	大数据可视化

    -	大数据促进医疗与健康

    -	大数据预测分析

    -	大数据优化交通

5. 大数据关键技术

    -	可视化技术

    -	机器学习

    -	人工智能

    -	分布式计算

    -	云技术: 云存储与云计算

    -	Hadoop 与 NoSQL

    -	Spark 

6. 大数据分析知识库

    -	统计知识

    -	编程语言 R

    -	编程语言 Python

    -	并行计算与分布式计算编程

    -	Web与Javascript

7. 大数据人才需求分析

    -	数据分析生命周期模型

    -	数据从事人员分类

    -	数据科学家的技能与素质

    -	数据科学的十大技能

    -	大数据人才市场现状

    -	大数据人才培养课程设置探索


### 参考资料

1. 周苏，王文，大数据导论，清华大学出版社，2016.9

1. 朝乐门，数据科学, 清华大学出版社，2016.8 

1. 朝乐门，数据科学理论与实践, 清华大学出版社，2017.10 

1. Joel Grus(高蓉，韩波译), 数据科学入门, 中国工信出版集团，人民邮电出版社, 2016.3

1. 王汉生，数据思维(从数据分析到商业价值)，中国人民大学出版社，2017.

1. 黄伟豪, 数据分析思维: 产品经理的成长笔记，机械工业出版社, 2017.10

1. 马继华, 大数据思维--从掷骰子到纸牌屋, 中国工信出版集团，电子工业出版社, 2016.7

1. 李鑫，数据产品经理: 从零经验到令人惊艳, 中国工信出版集团，电子工业出版社, 2018.4. 

1. Ian Anyres(宫相真译)，大数据思维与决策, 人民邮电出版社, 2014.10 

1. 毕马威中国大数据团队, 洞见数据价值: 大数据挖掘要案纪实，清华大学出版社, 2018.2

1. Bart Baesens (柯晓燕，张纪元译), 大数据分析: 数据科学应用场景与实践精髓, 中国工信出版集团，人民邮电出版社, 2016.1

1. 西内启(日)(李晨译)， 统计思维, 浙江人民出版社, 2017. 12

1. Lillian Pierson, Data science for dummies (2nd Ed.), 2017.3. E-Book.    

1. Frank Ohlhorst. Big data analytics --- Turning Big Data into Big Money. John Wiley & Sons. 2013. 

1. David Feinleib. Big data bootcamp --- What managers need to know to profit from the Big data revolution. Apress. 2014.

1. Kim H. Pries and Robert Funnigan. Big Data Analytics --- A Practical Guide for Managers. CRC Press. 2015. 

1. Russell Walker. From Big Data to Big Profits --- Success with Data and Analytics. Oxford University Press. 2015.

1.  Bernard Marr. Big data in practice---How 45 successful companies used big data analytics to deliver extraordinary results. Wiley. 2016.

---

## A-2. 统计分析基础

**课程性质**: 大数据分析基础系列

**大纲制定**: 汤银才

**课件开发**: 丁辉

**建议学时**: 2/周 授课 + 1/周 操练，共54小时 

### 课程介绍

- 数据是米，模型是水，想做出好吃的饭，还得用统计思想这把火。人们将广泛认识到：统计学是数据分析的灵魂，是互联网+信息化时代大数据科学的核心，是科学思想的中心成分之一。美国知名调查机构PayScale及CareerCast网站显示2016年和2017年最佳工作均与统计学相关。C.R.Rao教授：人类活动内的一切领域都要求统计学的专业知识和技术，统计思维总有一天会像读与写一样成为一个有效率公民的必备能力。

- 本课程共二大模块七个章节，分别从一维和二维数据角度讲述数据分析背后深刻的统计思想、基本原理和分析方法，让学员从理论高度了解数据呈现规律的统计描述、量化方法和推断技巧。

- 本课程是数据分析的基础课程，学员可以通过学习获得对数据的敏感性、统计模型的熟练性和数据分析结果解释的正确性。

### 课程目标: 

本课程旨在培养学生/学员

- 从数据的分布与相互关系上掌握统计建模的诀窍

- 诊断数据处理与分析存在的问题

- 进一步学习统计、用好统计

### 适合学生/学员：  

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**：一维数据的统计分析

1. 数据分析与统计思想

  	- 概率论与统计学

  	- 测量/误差与随机/分布

  	- 概率与计算

  	- 数据/随机变量与分布

  	- 独立与相关性

2. 描述性统计分析

  	- 总体与样本

  	- 中心趋势的度量

  	- 离散程度的度量

  	- 其他特征量: 偏度、峰度、极差、异常值

  	- 数据的图表展示

3. 统计推断

  	- 常用的统计分布

  	- 统计推断的基本问题

  	- 大数定律与中心极限定理

  	- 数据、参数与似然函数

  	- 统计检验、p值与功效

  	- 估计的精度与置信区间

4. 常用分布的统计推断

  	- 正态分布的推断：估计与拟合

  	- 区间估计与样本量的确定

  	- t分布与t检验: 单样本、两样本

  	- 二项分布的推断：估计与检验

  	- 泊松分布的推断：估计与检验

  
**第二部分**：二维数据的统计分析  

1. 二维数据的统计推断

  	- 二维数据的图形比较

  	- 相关性度量与计算

  	- 二维正态分布与特征量

  	- 二个正态总体的比较

  	- 二个比例比较

2. 线性回归

  	- 模型假设

  	- 简单线性回归

  	- 多元线性回归

  	- 数据变换

  	- 多项式回归

  	- 回归预测与变量选择

3. 方差分析

  	- 单因素方差分析

  	- 单因素协方差分析

  	- 双因素方差分析

  	- 重复测量方差分析

  	- 用回归做方差分析

### 参考资料

1. 贾俊平，何晓群，金勇进. 统计学(第五版). 中国人民大学出版社. 2012. 

1. 吴喜之, 刘超. 统计学: 从概念到数据分析(第二版). 高等教育出版社. 2016.4. 

1. 吴喜之. 统计学: 从数据到结论(第四版). 中国统计出版社. 2013. 

1. Larry Wasserman. All of Statistics--A Concise Course in Statistical Inference. 2003. (中译本---张波等. 统计学完全教程. 科学出版社. 2008.) [github上有习题的R/python代码]

1. David S. Moore， Willian I. Notz， Michael A. Fligner. The Basic Practive of Statistics (6th Ed.). W.H. Freeman and Company. 2013. 

1. David S. Moore，George P. Mc Cabe, Layth C. Alwan, Bruce A. Craig, Willian M. Duckworth. The Practice of Statistics for Business and Economics(3rd Ed.).  W.H. Freeman and Company. 2011. 

1. David S. Moore. 郑惟厚译. 统计学的世界(第五版). 中信出版社. 2001. 

1. David S. Moore， Willian I. Notz. Statisitics---Concepts and Controversies (7th Ed.). W.H. Freeman and Company. 2009. 

1. Kenneth Baclawski. 
[Introduction to Probability with R]
(http://stochas.com). CRC Press. 2008. 

1. G. Jay Kerns. [Introduction to Probability and Statistics Using R (IPSUR)](
https://cran.r-project.org/web/packages/IPSUR/vignettes/IPSUR.pdf). 2011. 

1. Alan T. Arnholt. 
[Probaility  and Statistics with R, 2nd Ed. (PASWR)](
http://www1.appstate.edu/~arnholta/PASWR/)

1. Daniel Navarro. 
 [Learning Statistics with R(lsr)]
(http://health.adelaide.edu.au/psychology/ccs/teaching/lsr/). 2015 [*]

1. Antony Unwin. 
Graphical Data Analysis with R. CRC Press.  2015

1. Peter Dalgaard. 
Introductory Statistics with R, 2nd ed (ISwR). 2002.

1. * Prabhanjan N. Tattar, Suresh Ramaiah, B.G. Manjunath.
A Course in Statistics with R(ACSWR), for master students. Wiley. 2016. 

1. Vincent Zoonekynd. 
[Statistics with R, gallary]
(http://zoonek2.free.fr/UNIX/48_R/all.html)


---

## A-3. 数据库与数据处理

**课程性质**: 大数据分析基础系列

**大纲制定**: 郞大为

**课件开发**: 郞大为

**建议学时**: 2/周 授课 + 1/周 操练，共54小时 

### 课程介绍

- 数据按照数据结构存储于数据库之中，并经过处理步骤实现数据的采集、检索、加工变换和传输。在当今大数据时代，除了传统的结构化数据，我们需要面临形形色色的非结构化的海量数据。IDC报告预测2020年全球的数据将超过40ZB，它们将根据不同的数据类型和数据量存贮在关系型与非关系型数据库数据库中。掌握数据库与数据处理的技能成为当今数据分析师必备的技能之一。

- 本课程共3大模块，分别从数据库、不同类型数据库的访问、数据的获取以及在R中的实现与数据整理等数据分析之前必须要具备的技能。

- 本课程为基础课程，经过学习，学员能够全方面掌握数据库、基于R的数据获取与数据处理的技能，并能将其运用到业务之中，解决实际问题。

### 课程目标:

本课程旨在培养学生/学员

- 全面掌握数据库有关的基础知识

- 使用R语言，实现对数据库的连接、数据的查询与读取等操作

- 能够熟练地使用与数据库与数据处理相关的R包进行数据分析前的准备工作

### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**：数据与数据库
      
1. 数据库基础

    - 数据的类型

  	- 数据的运算

  	- 结构化与非结构化数据

  	- 数据库简介

  	- 数据库操作语言

  	- 案例：火车时刻表的分析

2. 数据库操作

  	- SQL简介

  	- 常用SQL语法

  	- 数据表之间的关联

  	- SQL函数与Group

  	- 常用数据库简介

    - SQL汇总分析
  
  	- 案例: 电商销售数据

**第二部分**：数据的获取

1. R语言数据获取

  	- 读取文件中的数据

  	- 读取Excel数据表

     	  - RODBC
      	- xlsx
      	- readr

  	- 读取其他类型的数据

  	- 读取其他统计软件格式的数据(SAS, Stata, SPSS)

2. R与数据库的连接

  	- 使用RMySQL访问MySQL关系型数据库

        - 安装MySQL, RMySQL
        - 从MySQL读取数据
  	
  	- 基于DBI包访问数据库
    
        - RJDBC
        - ROracle
        - RPostgreSQL
        - RSQLite
  	
  	- 数据库操作: sqldf包简介
  	
  	- 从非关系型数据库NoSQL读取数据：RMongodb

3. 数据的爬取

    - 爬虫基础

    - 爬虫软件

    - 基于R的爬虫

    - 基于python爬虫

**第三部分**：基于R数据整理

1. 常规的数据处理包   

    - dplyr
    
        - dplyr的基本函数
        - 数据汇总,数据连接
        - dplyr连接数据库
    
    - 案例: 使用dplyr整理汽车经销商数据
  
2. 更强易用的数据处理包

    - tidyr 长宽数据的转化

        - gather() 数据变形，制作长型数据
        - spread() 数据转换，制作宽型数据

    - data.table：更快地完成数据集的数据处理

    - reshape2：数据的变形与汇总
  
    - plyr：数据的拆分、应用、合并
  
    - lubridate：处理时间数据

### 参考资料

1. Hadley Wickham, Garrett Grolemund, R for Data Science - Import，Tidy，Transform，Visualize, and Model data,  O'Reilly. 2017.

1. Djoni Darmawikarta, Learning SQL Queries for R User, 2016.

1. Bradley C. Boehmke, Data Wrangling with R, Springer, 2016. 

1. Jacqueline Kazil & Katharine Jarmul,  Data Wrangling with python, OREILLT, 2016.

1. Nicholas J. Horton and Ken Kleinman,  Using R and RStudio for Data Management Statistical Analysis and Graphics, CRC Press, 2015. 

1. Jared P. Lander, R for Everyone --- Advanced Analytics and Graphics, Addison-Wesley,  2014. [*]

1. Joseph Adler,  R in a Nutshell (2nd Ed.), OREILLY, 2012.9

1. Wes McKinney, Python for Data Analysis(2nd Ed.)---
Data Wrangling with Pandas, NumPy, and IPython, ORELLY, 2018. 

1. Deborah Nolan and 
Duncan T. Lang,  XML and Web Technologies for Data Sciences with R, Springer, 2014.

1. Data Wrangling: Munging in R with SQL and MongoDB for Financial Applications, Apress (eBook), 2018. 

1. Tye Rattenbury et al., Principles of Data Wrangling: Practical Techniques for Data Preparation, 2017-07

1. Allan Visochek, Practical Data Wrangling: Expert techniques for transforming your raw data into a valuable source for Analytics (Kindle edition), PACKT, 2017. 

- data-wrangling-cheatsheet

- six-core-data-wrangling-activities-ebook

- Data Munging With R

- CSIRO-A few data manipulation tricks




---

## A-4. R语言基础

**课程性质**: 大数据分析基础系列

**大纲制定**: 汤银才

**课件开发**: 汤银才，张东

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- R语言是一个自由、免费、源代码开放的语言环境。它功能完备，语言灵活且不依赖操作系统，是一个用于统计计算和统计制图的优秀工具。在2010 年，美国统计协会（ ASA）授予R 语言为(第⼀届)统计计算及图形奖。截止目前为止，R是数据科学领域使用用户最多的数据挖掘与编程语言，且其用户数量在不断增加。R已经成为几乎所有国内外高校统计类课程标配的教学软件，R的书集遍及经济、金融、生物、医学、生态、电子商务、航空、旅游、心理、法律等各个领域，并成大数据分析的宠儿: 覆盖机器学习、人工智能和可视化等。R语言在国内业界也逐步成为主流的分析工具，每年全国性的R语言会议推进R的迅猛发展。

- 本课程共5大模块，从R入门、R数据集创建与管理、R绘图初步、R数据探索与比较分析和R统计建模等方面，让零基础学员从各个角度对R的使用进行学习。

- 本课程为基础课程，学员可以通过学习对R语言进行全方位的了解与掌握，并为R的进阶学习与实际数据分析做好基础铺垫。

### 课程目标:

本课程旨在培养学生/学员

- 从零开始对R语言进行全方位的基础掌握

- 使用R语言进行基本的数据分析与可视化

- 为R语言进阶学习提供基础

### 适合学生/学员：

数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**：R入门

1. 大数据与数据科学

    - 数据科学与分析工具

  	- R及其优势

  	- R安装与配置

  	- R包安装与使用

  	- R资源与帮助

2. R快速入门教程

  	- R中的基本语法

  	- R中的数据对象及其属性

  	- R的工作空间与管理

  	- R编程基础

  	- R程序调试

3. RStudio与文学化编程

  	- R常用编辑器

  	- Rstudio功能与使用技巧

  	- Rstudio进阶

  	- 项目管理
  	
  	- Rmarkdown与报告生成

**第二部分**：R数据集创建与管理

1. 数据集的创建与处理

    - 常用数据对象与创建
    
        - 标量
      	- 向量
      	- 因子
      	- 矩阵
      	- 数据框
      	- 数组
      	- 列表
    
    - 数据的读取

    - 数据的存储

    - 数据集的处理

    - 数据集的合并与子集提取

    - 缺失值的处理

    - 数据表数据的切片、切块与组合

2. 向量的操作

    - 合并数据框的行(向量)与列(向量)
  	
  	- apply系列函数 
  	
  	- 数据分组并调用函数
  	
  	- 数据拆分与合并
  	
  	- 数据排序
  	
  	- 访问数据中的列
  	
  	- 查找符合条件的数据索引
  	
  	- 分组运算

3. 数据对象的其他操作

    - 赋值与常用运算
  	
  	- 基本的数学运算
  	
  	- 用于矩阵的运算
  	
  	- 正则表达式
  	
  	    - 字符数统计和字符翻译
  	    - 字符串连接
  	    - 字符串拆分
  	    - 字符串查询
  	    - 字符串替换
  	    - 字符串提取

  	- 与统计分布相关的函数

      	- 概率

      	- 密度/质量

      	- 分位数

      	- 随机数产生

**第三部分**：R绘图初步

1. 基本的绘图命令

  	- 大趋势：信息可视化

  	- R绘图基础: 低级与高级绘图命令

  	- 基本绘图函数: plot, points, lines, curve，par

  	- 绘图三要素设置详解(颜色，点型，线型)

  	- 绘图信息补充(title,text,legend,axis)
  	
  	- R窗口和图形设备（X11，pdf，png）

2. 一维数据的可视化

  	- 常用统计分布与4类函数

  	- 一维离散变量的分布图示

    - 一维连续变量的分布图示
  	
  	- 一维连续分布诊断图
  	
  	- 非参数密度估计与展示

3. 多维数据的可视化

  	- 二个离散变量的分布图示

  	- 二个混合变量的分布图示

  	- 二个连续变量的分布图示

    - 多变量的可视化

**第四部分**：R数据探索与比较分析

1. 数据的描述性统计分析

  	- 常用描述性统计量及其计算
  	
  	- 单个连续型变量描述性统计量的获取

  	- 分组计算描述性统计量

2. 相关性度量

    - 变量的类型与转换
    
    - 两个定性变量之间的关联性
    
    - 两个有序变量之间的关联性
    
    - 两个定量变量之间的关联性
    
    - 定性变量与定量变量之间的关联性

3. 相关性检验

   	- 组间差异比较

      	- 独立样本的t检验
      	- 非独立样本的t检验
      	- 组间差异的非参数检验
    
    - 分类变量比较
        
        - 列联表的生成
        - 联合分布、边际分布与条件分布
        - 独立性检验(1)：卡方检验
        - 独立性检验(2)：Fisher精确检验
        - 独立性检验(3)：McNemar检验
        - 独立性检验(4)：Cochran-Mantel-Haenszel检验

**第五部分**：R统计建模

1. 回归模型

  	- lm()函数中的公式表示

  	- 一元线性回归

  	- 多元线性回归

  	- 回归预测

  	- 分位数回归

2. 分类数据的统计推断

  	- 广义线性模型概述
  	
  	- glm()函数介绍

  	- Logistic回归

  	- Poisson回归

3. 模型的检验与比较
    
    - 回归模型诊断

    - 变量的选择

    - 模型比较

    - 异常值判断

    - 预测与交叉验证 


### 参考资料

1. R.I. Kabacoff著, 高涛,肖南, 陈钢译, R语言实战(R in Action: Data Analysis and
Graphics with R), 人民邮电出版社, 2013.

1. 徐珉久[韩], 武传海 (译). R语言与数据分析实战. 中国工信出版集团，人民邮电出版社, 2017.1

1. 汤银才, R语言与统计分析, 高等教育出版社. 2008

1. Joseph Adler, R in a Nutshell, California: O’Reilly Meda, Inc., 2nd Ed. 2012. 

1. Jared P. Lander, R for Everyone: Advanced Analytics and Graphics. New York: Addison-Wesley. 2014.

1. Hadley Wickham, Garrett Grolemund, R for Data Science - Import，Tidy，Transform，Visualize, and Model data, O'Reilly. 2017. 

1. Jim Albert, M. Rizzo, R by example, Springer, 2012. 

1. Prabhanjan N. Tattar, Suresh Ramaiah, B.G. Manjunath. A Course in Statistics with R(ACSWR), for master students. Wiley. 2016. [*] 

1. Norman Matloff.  The art of R programming, No Starch Press, inc., 2011.

1. Paul Murrell, R Graphics, Chapman & Hall/CRC. 2006.

1. Deepayan Sarkar, Lattice: Multivariate Data Visualization with R, Springer. 2008.

1. Hadley Wickham, ggplot2: Elegant Graphics for Data Analysis, Springer. 2009. (中译本: 殷腾飞,统计之都, 2014)

1. Donato Teutonico, ggplot2 Essentials, PACKT, 2015. 

1. Alboukadel Kassambara, ggplot2 - Guide to Create Beautiful Graphics in R (2nd Ed). 2013. 

1. Mark P.J. van der Loo, Edwin de Jonge, Learning Rstudio for R Statistical Computing. PACKT,  2012. 

1. John Verzani, Getting Started with Rstudio, OReilly, 2011. 

1. Nicholas J. Horton and Ken Kleinman. Using R and RStudio for Data Management Statistical Analysis and Graphics(2nd Ed.)，2015.




---

## A-5. Python基础

**课程性质**: 大数据分析基础系列

**大纲制定**: 汤银才, 李浩

**课件开发**: 尹志，李浩

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 近两年来，数据分析师的岗位需求非常大，90%的岗位技能需要掌握Python作为数据分析工具，Python语言的易学性、快速开发，拥有丰富强大的扩展库和成熟的框架等特性很好地满足了数据分析师的职业技能要求。

- 本课程共四大模块，内容包括Python基础语法、数据处理相关模块以及统计分析模块详细讲解，并通过实际案例观察Python语言在数据分析行业中的广泛应用，让学员体验Python语言的强大功能。

- 本课程是数据分析的基础课程，学员可以通过学习获得Python语言使用的基本方法以及一些数据处理模块的使用方法。

### 课程目标:

本课程旨在培养学生/学员

- 从零开始熟练掌握Python基本语法，并能够应用。

- 熟悉Python计算模块、数据处理模块和可视化模块的使用。

- 能够运用统计分析模块解决实际案例。

### 适合学生/学员：

数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**：数据分析方法概述及相关工具

1.	认识数据

2.	数据分析的步骤与原则（确定/分解/评估/决策）

3.	相关工具概述与对比（Excel/SPSS/R/Matlab/Python/Java）

4.	平台使用

**第二部分**：Python环境和基础语法

1.	安装anaconda套件

2.	基本数据结构

3.	Python notebook使用

4.	基本语法

5.	迭代器

6.	函数

7.	Python在业界的应用案例分享

**第三部分**：数据操作与计算

1.	numpy数组与操作

2.	numpy统计函数

3.	numpy线性代数

4.	科学计算和最优化(scipy)

5.	强大灵活的数据结构 pandas DataFrame


**第四部分**：绘图与可视化

1.	matplotlib中绘图

2.	pandas中绘图

3.	Charts中绘图

4.	ggplot, seaborn

5.	交互式可视化bokeh

6.	在线工具plot.ly

7.	高级应用案例分享

8.	绘制地图

9.	绘制3D图形

**第五部分**：统计分析库（StatsModels）

1.	概率和统计分析

2.	时间序列模型

3.	简单线性回归

4.	多元线性回归

5.	logistic回归

### 参考资料

1. Mark Lutz著, 李军, 刘红伟[译], Python学习手册(4th Ed.), OREILLY/机械工业出版社, 2011. 

1. Wes McKinney, Python for Data Analysis(2nd Ed.)---
Data Wrangling with Pandas, NumPy, and IPython, ORELLY, 2018. 

1. Luca Massaron and John Paul Mueller, Python for Data Science For Dummies, Wiley, 2015. 

1. Ivan Idris, Python Data Analysis, PACKT, 2014.

1. Luca Massaron and Alberto Boschetti, Regression analysis with python， PACKT, 2016.

1. Anita Raichand, Practical Data Analysis with Python， 2015. 

1. José Unpingco, Python for Probability, Statistics, and Machine Learning，Springer, 2016. 

1. Thomas Haslwanter， An Introduction to Statistics with Python---With Applications in the Life Sciences， Springer, 2016. 

1. Alexandre Devert， matplotlib Plotting Cookbook，PACKT,  2014.

1. Igor Milovanovic, Python Data Visualization Cookbook， PACKT, 2013. 

1. Alberto Boschetti and Luca Massaron, Python Data Science Essentials， PACKT, 2015.

1. Brendan Scott, Python for kids for Dummies, Wiley, 2015. 

1. Rui Sarmento and Vera Costa， Comparative Approaches to Using R and Python for Statistical Data Analysis， IGI, 2017. 

1. Statistical Data Analysis in Python, 2015.  [github](https://github.com/fonnesbeck/statistical-analysis-python-tutorial)

---

# Series II/中级系列

## B-1. 数据可视化

**课程性质**: 大数据分析中级课程系列

**大纲制定**: 谢佳标，汤银才

**课件开发**: 谢佳标

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 随着DT时代的到来，传统的统计图表很难对复杂数据进行直观地展示。这几年数据可视化作为一个新研究领域也变得越来越火。成功的可视化，如果做得漂亮，虽表面简单却富含深意，可以让观测者一眼就能洞察事实并产生新的理解。本培训课程将介绍R语言做数据可视化的相对高端的统计分析方法，为大数据的实际应用打下坚实的统计基础。

- 本课程共四大模块，主要讲述R绘图品质的提升，常用绘图系统介绍，高维数据可视化，统计机器学习中的数据可视化。让学员学会如何用R绘制出漂亮的静态和动态图形。

- 通过本课程的学习，学员可以掌握lattice和ggplot2的两大R语言绘图系统、交互式绘图技术以及统计机器学习的数据可视化。

### 课程目标:

本课程旨在培养学生/学员

- 掌握R的数据可视化基础和两大绘图系统

- 掌握动态交互式图形的绘制，实现信息的多维度表达

- 掌握R数据可视化在统计和机器学习中的应用，在实际数据分析问题建模过程结束后用可视化展现结果。

### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**. 绘图品质的提升

1. R绘图系统

 	  - R graphics基本绘图命令(复习)

    - 区域分割与绘图

    - 图形输出常见问题处理

    - 常用统计图形在不同绘图系统中的比较

2. 图形的渲染

    - rainbow函数
  	
  	- 高质量图形渲染库Cairo
  	
  	- RColorBrewer扩展包
  	
  	- scales: brewer.pal

**第二部分**: 常用绘图系统介绍

1. lattice绘图系统

    - 一个简单的lattice例子
  	
  	- 图形参数设置
  	
  	- - 面板函数
  	
  	- 图形的叠加：条件变量与条件变量设置
  	
  	- 其他常用统计图

2. ggplot2绘图系统

    - 最简单的绘图函数：qplot
    
    - ggplot2的语法：以散点图为例
  	
  	- 图层与统计图展示
  	
  	- ggthemes主题包介绍
  
**第三部分**: 高维数据可视化  

1. 3D可视化

    - 3D静态可视化基础

    - 3D静态可视化提高

    - 常用动态3D可视化包介绍
  	
  	- 动态3D散点图
    
    - 基于RGL 3D可视化

2. 交互式绘图包

    - rCharts（nPlot, hPlot, mPlot）
  	
  	- recharts
  	
  	- plotly
  	
  	- bokeh/rbokeh
  	
  	- REmap

3. R中的仪表盘

	  - flexdashboard

	  - shinydashboard 

	  - shiny仪表盘应用: 美国大选数据可视化

	  - PowerBI中使用R制作仪表盘

**第三部分**. 统计机器学习中的可视化

1. 多元统计中的可视化

    - PCA可视化(FactoMineR)
   	
   	- CA与MCA可视化(FactoMineR)
  	
  	- 基于Factoshiny函数的可视化
    
    - 时间序列绘图(时间为条件变量，分组变量，补充变量)

2. 基于GIS的动态可视化  

    - 能用地图
   	
   	- googleVis
    
    - RgoogleMaps
   	
   	- 空间数据绘图(热图，参考图，物理图)
   	
   	- 时空数据绘图
   	
   	- 案例：R语言天气可视化应用

### 参考资料

1. Richard Brath and David Jonker, Graph Analysis and Visualization---Discovering Business Opportunity in Linked Data, Wiley, 2015. 

1. Thomas Rahlf. Data Visualisation with R 100 Examples, Springer, 2017. 

1. Jodie Burchell & Mauricio Vargas， The Hitchhiker's Guide to ggplot2 in R, Learnpub, 2016.

1. Hadley Wickham, ggplot2: Elegant Graphics for Data Analysis, Springer(2nd Ed.). 2016. (中译本: 殷腾飞,统计之都, 2014)

1. Donato Teutonico, ggplot2 Essentials, PACKT, 2015. 

1. John J. Hilfiger, Graphing Data with R. Oreilly, 2016.

1. Antony Unwin, Graphical Data Analysis with R, CRC Press, 2015. 

1. Kevin J. Keen, Graphics for statistics and data analysis with R， CRC Press, 2010.

1. Dwight Barry， Business Intelligence with R，2016. 

1. Francois Husson, Sebastien Le and Jerome Pages, Exploratory Multivariate Analysis by Example Using R， CRC, 2017. 

1. Alboukadel Kassambara, ggplot2 - Guide to Create Beautiful Graphics in R (2nd Ed). 2013. 

1.  Keon-Woong Moon, Learn ggplot2 using Shiny App, Springer， 2016. 

1. *Julian Hillebrand and Maximilian H. Nierhoff, Mastering RStudio – Develop, Communicate, and Collaborate with R， 2015.

1. Andrea Cirillo. RStudio for R Statistical Computing Cookbook，PACKT, 2016. 

1. Marta Blangiardo and Michela Cameletti, Spatial and Spatio-temporal Bayesian Models with R-INLA, Wiley, 2015. 

1. Oscar P. Lamigueiro, Displaying Time Series, Spatial, and Space-Time Data with R, Chapman & Hall/CRC, 2014. [Source at github](https://github.com/oscarperpinan/spacetime-vis)  

1. Alboukadel Kassambara， Complete Guide to 3D plots in R-Static and interactive 3-dimension graphs， sthda.com, 2015.

1. Dianne Cook and Deborah F. Swayne, Interactive and Dynamic Graphics for Data Analysis---with R and GGobi， Springer, 2007. 

1. Tom Barker, Pro Data Visualization using R and JavaScript，APRESS,  2013. 

1. Nick Qi Zhu, Data Visualization with D3.js Cookbook， PACKT, 2013. 

* Scott Murray, Interactive Data Visualization for the Web， OREILLY, 2013. 

* Web Application Development with R Using Shiny, 2013.

* Programming Graphical User Interfaces with R, 2012. 

---

## B-2. 高级统计分析

**课程性质**: 大数据分析中级课程系列

**大纲制定**: 汤银才

**课件开发**: 丁辉

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 现在是数据为王的时代，大数据这个概念“忽如一夜春风来，千树万树梨花开”，以迅雷不及掩耳之势进入人们的视野。当今时代，数据的火热，更加强调了数据分析在这个时代的重要性，掌握数据统计、数据分析和解读数据的技术尤为重要。本培训课程将介绍相对高端的统计分析方法，为大数据的实际应用打下坚实的统计基础。

- 本课程共六个章节，分别列举了实际常见的统计问题，主要讲述时间序列分析、分类和聚类、高维数据的变量选择及其模型选择、抽样方法、最优化方法和空间统计分析的基本流程及其背后蕴藏的统计思想和分析方法，让学员从理论高度熟悉和掌握数据分析、推断的技巧和方法。

- 本课程是数据分析基础的后继课程，学员可以通过学习掌握常用的统计模型和数据分析的技巧及其结果的解释。

### 课程目标:

本课程旨在培养学生/学员

- 深入了解复杂数据分析的统计思想和统计方法

- 开阔统计思维，用更高级的模型处理与高维数据相关的实际问题

- 奠定后续学习机器学习及深度学习课程必要的统计基础

### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**: 时间序列分析

1. 时间序列概述

    - 时间序列的特征
    
    - 时间序列的描述性分析
    
    - 白噪声与平稳性

2. 平稳时间序列模型

    - AR模型
 
    - MA模型
    
    - ARMA模型

3. 非平稳序列模型

    - ARIMA模型
 
    - 季节效应模型

4. 异方差模型

    - ARCH模型
    
    - GARCH模型
    
    - EGARCH模型
    
    - SV模型

**第二部分**: 多元统计分析

1. 多变量回归      

    - 多变量回归分析
    
    - 协方差分析

2. 多变量降维

    - 岭回归与Lasso回归

    - 主成分分析

3. 多变量分类

    - 判别函数

    - 分类问题

    - 聚类分析

**第三部分**: 重抽样方法

1. 随机数据的产生

    - 常用随机数据的产生
 
    - 重要性抽样

2. 蒙特卡罗方法

    - 蒙特卡罗积分与方差减少技术
    
    - bootstrap方法
    
    - jackknife方法

**第四部分**: 最优化方法

1. 极值问题
 	
 	  - 极大似然估计
    
    - 一维最优化问题及其求解
    
    - 多维最优化问题及其求解
    
    - Laplace近似
    
    - EM算法

2. 其他优化算法

   - 线性规划

   - 遗传算法

   - 图优化

**第五部分**: 空间统计分析

   - 空间数据的收集与整理

   - 空间数据的自相关性
   
   - 空间自相关性度量
   
   - 空间自相关数据的多元分析
      
      - 回归分析
      - PCA
      - 回归树
      - 随机森林

### 参考资料

---

## B-3. 贝叶斯分析与应用

**课程性质**: 大数据分析中级课程系列

**大纲制定**: 汤银才

**课件开发**: 丁辉

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 英国学者托马斯·贝叶斯在《论有关机遇问题的求解》中提出一种归纳推理的理论，后被一些统计学者发展为一种系统的统计推断方法，称为贝叶斯方法。采用这种方法作统计推断所得的全部结果，构成贝叶斯统计分析的主要内容。时至今日，其影响日益扩大。现今的贝叶斯网络，贝叶斯分类器乃至深度学习，都与贝叶斯理论分析息息相关。

- 本课程共四大模块，从贝叶斯方法分析入门、提升、贝叶斯常用模型和方法应用四个方面对贝叶斯方法分析这一领域进行深刻解读。

- 通过本课程的学习，学员可以掌握区别于频率学派的贝叶斯学派分析方法理论，并通过统计软件加以实践，从而解决实际业务问题。

### 课程目标:

本课程旨在培养学生/学员

- 掌握贝叶斯方法的思想和理论知识

- 灵活运用贝叶斯分析与软件解决实际问题

- 奠定后续进行学习计器学习及深度学习课程必要的基础

### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**: 贝叶斯分析入门

1. 贝叶斯分析概述

    - 先验信息与提取
    
    - 贝叶斯公式
    
    - 后验推断
    
        - 估计: 后验均值与可信区间
        - 检验: 变量选择与模型比较
        - 预测: 先验与后验预测
 
 2. 单参数贝叶斯模型
 
    - 二项分布: 成功率
    
    - 正态分布: 均值/方差
    
    - 指数分布
    
    - 泊淞分布

**第二部分**: 贝叶斯分析提高

1. 多参数贝叶斯模型     

    - 正态分布

    - 多项分布

2. MCMC方法

    - 贝叶斯计算

    - 抽样方法

    - M-H算法

    - Gibbs抽样

    - 常用的M-H算法

3.  MCMC软件: 

    - BUGS, WinBUGS, OpenBUGS及在R中的实现 

    - JAGS与rjags, runjags

    - Stan与rstan

**第三部分**: 实用贝叶斯模型

1. 回归模型

    - 线性模型

    - 最小二乘估计

    - 基于Jeffreys先验分析

    - 基于G-先验分析

2. 广义线性模型

    - logit模型

    - Probit模型

    - 对数线性模型

3. 分层贝叶斯模型

    - 分层贝斯模型的构建

    - 正态分布

    - logistic回归模型

4. 混合模型

    - 有限混合 

    - EM解决方法

    - MCMC解决方法

    - 未知混合个体问题
    
**第四部分**: 贝叶斯方法的应用

1. 时间序列分析

    - AR模型

    - MA模型

    - ARMA模型

    - 隐马尔可夫模型

2. Capture-Recapture模型 

	  - 通常的Capture-Recapture模型的贝叶斯分析

	  - 空间Capture-Recapture模型的贝叶斯分析

3. 贝叶斯方法在机器学习中的应用

    - 过拟合与模型平均
    
    - 贝叶斯分类: 

        - 朴素贝叶斯分类
        - logistic模型

    - 文本分析

    - 贝叶斯混合模型

    - 主题模型

    - 贝叶斯神经网络

4. 贝叶斯网络

    - 有向无圈图

    - 贝叶斯网络
        
        - 离散场合
        - 连续场合

5. 大数据时代的贝叶斯分析

### 参考资料

---

## B-4. 统计机器学习

**课程性质**: 大数据拓展系列

**大纲制定**: 汤银才

**课件开发**: 魏鹏

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 目前，机器学习可谓业界最为火热的一项技术。 随着计算机与网络的快速发展，机器学习在我们的生活和工作中起着越来越大的作用，正在改变着我们的生活和工作。从日常使用的相机，每天使用的搜索引擎，网上的每一次购物，到无人驾驶汽车，智能家居，智能机器人等，都有机器学习的影子。 继Facebook开源人工智能系统TensorFlow，2015年11月，谷歌、微软、IBM纷纷开源其机器学习工具包，以便加快机器学习的发展与应用。机器学习正在从少为人知的技术主题转变成更多人使用的管理工具。

- 本课程共五大模块九个章节，分别从数据挖掘、聚类分析和分类三大角度讲述机器学习背后的数据挖掘过程和应用，聚类分析的方法模型以及分类的具体方法和应用，让学员从理论和实践高度更深刻地了解和运用机器学习数据挖掘方法。

- 本课程以R和高维统计分析为基础，致力于培养有志于成为更高层次机器学习、数据挖掘方面人才的数据分析师。

### 课程目标:

本课程旨在培养学生/学员

- 获取进一步学习高级统计、用好高级统计的知识

- 利用R学习机器学习领域的数据挖掘、聚类分析、分类等内容

- 通过实例，实现机器学习的应用


### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......


### 课程大纲

**第一部分**：认识数据挖掘

1. 数据挖掘概述

  	- 数据挖掘过程
  	
  	- 数据挖掘对象
  	
  	- 数据挖掘方法
  	
  	- 数据挖掘应用
  	
  	- 无监督与有监督学习
  	
  	- 机器学习常用R包简介
  	    
  	    - e1071
  	    - caret
  	    - H2O
			
2. 模型评估与选择

  	- 分类的性能评价

  	- 混淆矩阵

  	- 风险图

  	- ROC曲线及相关图表(plotroC, pRoC, ROCR)

  		  - 利用caret包比较ROC曲线
    
    - 交叉验证
  	
  		- K折交叉验证基本原理
  		- 利用e1071包完成交叉验证
     	- 利用caret包完成交叉验证
  
**第二部分**： 聚类分析 

1. 几类常用的聚类方法

  	- K-means

  	- K-medoids

  	- 系谱聚类

  	- 密度聚类

  	- 期望最大化聚类

    - 相关R包: cluster

  	- 实例

2. 隐变量模型

  	- 概述

  	- 混合模型

  	- 隐马尔柯夫模型

  	- 聚类分析

  	- 实例

**第三部分**： 线性分类器 

1. 判别分析

   - 判别函数
      
      - 线性判别函数
      - 二次判别函数

  	- 朴素贝叶斯分析
  	
  	- rocchio算法
  	
  	- 相关的R包: caret
  	
  	- 实例

2. 支持向量机
    
    - 基本原理
    
    - 相关R包
    
    - 可视化分析

**第四部分**：非线性分类器

1. kNN

2. 决策树

    - 树的构建
    
    - 分类回归树CART
    
    - C4.5/5.0
    
    - 相关的R包: rpart
    
    - 实例

3. 随机森林

    - 基本原理
    
    - 相关的R包
    
        - randomForest
        - randomForestSRC
        - ggRandomForests
        - gbm
        - glmnet
        - ranger

3. 可视化分析

**第五部分**: 集成学习

  - Bagging
    
  - AdaBoost
    
  - xgboost
  
### 参考资料


---

## B-5. 网络爬虫与文本挖掘

**课程性质**: 大数据拓展系列

**大纲制定**: 尹志

**课件开发**: 尹志，靳军

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 随着网络的迅速发展，万维网成为大量信息的载体，如何有效地提取并利用这些信息成为一个巨大的挑战。网络爬虫，追求大的覆盖性与内容的精准性，按照一定的规则，自动地抓取万维网信息的程序或者脚本，能为用户提供大量的网络数据信息。同时，当今大数据的迅猛发展，数据并不仅仅以“数值”的方式存在，越来越多的文本信息等待人们去分析与利用，文本挖掘基于此背景孕育而生。它主要通过各种算法对文本进行数据挖掘，提取有用的信息，为使用者抓取价值与利润。

- 本课程分为四大版块，分别介绍并深入学习网络爬虫与文本挖掘的若干算法与实践，帮助学员全方位掌握这两大数据分析的重要模块。

### 课程目标:

本课程旨在培养学生/学员

- 获取待爬网页的关键信息

- 掌握爬取指定网页内容的技能

- 掌握挖掘文本数据信息的常用算法


### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程介绍

**第一部分**: 网络爬虫基础

1. 技术准备

    - 网络通信基础

    - HTTP协议简介

    - Web开发知识介绍

    - 网站分析知识介绍

2. 开发环境与语言

    - 开发环境安装与使用（Anaconda套件与PyCharm）

    - Python基础数据结构（元组/列表/字符串/字典）

    - Python基础语法（条件/循环/函数/类/模块）

    - 常用Python库使用案例分享

    - Python技巧与实践分享

**第二部分**： 数据爬取与存贮   

1. 网络爬虫工具库

    - 基础Python爬虫库（urllib/Requests）

    - 认识正则表达式

    - “漂亮”的爬虫库-Beautiful Soup

    - 静态网页爬取案例分享

    - Selenium与“幻影”浏览器- PhantomJS

    - Ajax和DHTML网站爬取

    - 动态网页爬取案例分享

    - 利用API进行数据采集

2. 网络爬虫存储

    - 文件读取与保存

    - 关系数据库存储-MySQL

    - 爬虫配合MySQL存储案例分享

    - 分布式存储-NoSQL数据库

    - 爬虫配合MongoDB存储案例分享

    - HDFS简介

**第三部分**: 网络爬虫提升

1. 分布式爬虫

    - 多线程爬虫

    - 多进程爬虫

    - 爬虫队列设计

    - 集群化爬取

2. 网络爬虫框架

    - Python网络爬虫框架介绍

    - Scrapy基本使用

    - Scrapy进阶使用

    - 爬虫框架使用案例分享

3. 网络爬虫突破

    - 模拟登录

    - 常见验证码突破

    - 爬虫代理池

    - 各类网页内容处理

    - 爬取移动端APP技巧

    - 设计健壮的网络爬虫

**第四部分**: 文本挖掘

1. 文本挖掘技术基础

    - 文本挖掘全流程概述

    - 自然语言处理库（NLTK）

    - TextBlob文本处理库介绍

    - 中文分词介绍（jieba）

    - 词云介绍

2. 文本挖掘技术进阶

    - 文本挖掘预处理技术

    - 文本特征处理

    - 文本聚类

    - 主题模型

    - 基于深度学习的文本挖掘

    - 文本挖掘案例分享


### 参考资料


---

# Series III/拓展系列

## C-1. 数据治理

**课程性质**: 大数据拓展系列

**大纲制定**: 汤银才

**课件开发**: 郞大为??

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 大数据时代数据产生的价值越来越大。如何将海量数据应用于决策、营销和产品创新？如何利用大数据平台优化产品、流程和服务？如何利用大数据更科学地制定公共政策、实现社会治理？所有这一切，都离不开大数据治理。可以说，在大数据战略从顶层设计到底层“落地”过程中，治理是基础，技术是承载，分析是手段，应用是目的。如果没有数据治理，再多的业务和技术投入都是徒劳，因为数据质量不过关只能是Garbage in Garbage out。数据治理是保证数据质量的必需手段，从全球范围来看，加强数据治理提升数据质量已成为企业提升管理能力的重要任务。

- 数据治理是一个系统的、大型的、长期的工程，大型企业已经开始了实施，并取得了一定成果，但目前高校和其他企业还没有开始真正意义上的实践。究其原因，一方面还没有把数据治理的重要性提升到战略高度，另一方面没有将数据治理单独作为课题研究，没有形成系统的实施方法论。

- 本课程从管理和技术两方面出发探索适合高校信息化建设的数据治理方法，形成包含组织、制度、标准、流程、安全、技术等内容的数据治理方案，从而打造高校绿色数据生态环境，为数据应用提供基础保障。

### 课程目标:

本课程旨在培养学生/学员

-	对数据治理的整体和各知识领域有总体认识

-	对关键领域的重点、难点、行业实践有深度理解

-	具备结构化的数据治理问题思考分析、方案设计、执行能力


### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**：数据治理概述

1. 什么是数据治理？

    - 基本概念

    - 数据治理的背景和现状  

    - 大数据环境对数据治理的影响分析

2. 数据治理策略 

    - 数据治理要素 

    - 数据治理策略 


**第二部分**：元数据管理 

1. 元数据的定义 

2. 为什么要进行元数据管理 

3. 数据模型标准化

4. 标准化体系(数据定义&模型设计)  

**第三部分**：主数据 

1. 主数据的定义 

2. 为什么要作主数据管理 

3. 如何做好主数据管理 

4. 主数据实施流程 

5. 主数据管理体系

**第四部分**：数据质量管理 

1. 数据质量问题 

2. 组织架构设计 

3. 数据质量治理流程 

4. 数据治理管理方法 

5. 最佳实践案例 
 
### 参考资料


---

## C-2. 深度学习

**课程性质**: 大数据拓展系列

**大纲制定**: 史春奇

**课件开发**: 史春奇

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 深度学习、人工智能引发了智能革命， 堪比以前的工业革命和电力革命。Google，Microsoft, Facebook等诸多信息科技巨头都已争相在此技术上投入前所未有的重视力度和战略资源。随着深度学习技术在学术界和工业界得到广泛认可，越来越多人开始参与到深度学习的相关研究和实践上。然而，由于存在一定的技术门槛快速入门深度学习的研究并不容易。其中一个原因就是深度学习许多问题不仅仅依赖实际操作，也依赖强有力的理论支撑。

- 本课程共4个部分，分别从深度学习背景、深度神经网络、深度学习应用和深度学习实践来讲述。 深入浅出的概述了深度学习的主流模型和应用。让学员不仅理解网络模型的结构，而且更好将深度学习应用到实际工作生活中。

- 本课程是大数据分析的高级课程，学员可以学会深度学习在有监督学习和无监督学习的应用，各种网络模型的结构和推断，以及在自然语言处理和图像处理中的应用。

- 本课程的设计充分结合了理论，应用，技术框架和案例分析，以及在公有云上的实操环境。

- 本课程是和亚马逊专家团队及合作伙伴共同打造，课程的教学完全基于目前全球最领先的亚马逊云平台并提供与各种深度学习所需要的云实操环境。

- 本课程的目标不仅让学员对深度学习有完整的理解，而且让学员能够切身体验各类云服务的应用，比较各种云计算能力对深度学习的影响，以及如何利用云服务来构建新型的AI应用。

- 本课程提供了标准化的云端授课环境及多种接入手段，学员无需顾虑本地电脑的计算能力及兼容性问题；云端授课大大提高了学员和老师高效的沟通交流；理论学习和动手操作的同步进行，保证了学员的学习效果。


### 课程目标:

本课程旨在培养学生/学员

- 熟悉深度学习的前世今生

- 掌握各种深度学习模型的要旨

- 掌握深度学习在文本、图像中的应用

- 入门深度学习的工程实践


### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程介绍

**第一部分**: 背景知识与基础

1. 深度学习简史 

2. 数学与算法基础

    - 概率分布基础：如何理解分布

    - 优化求解基础：如何理解梯度下降 

3. 人工神经网络基础

    - 感知器基础
	  
	  - 激活函数
	  
	      - sigmoid
	      - tanh
	      - ReLU
	      - ......
	  
	  - 反向传播算法的理解与详细推导

    - 梯度消失、爆炸/Gradient Vanishing、Explosion

**第二部分**: 深度神经网络理论

1. 卷积神经网络CNN

    - CNN结构

    - 卷积操作和池化操作

    - 如何理解CNN

2. 循环神经网络RNN 
    
    - RNN结构
    
    - 三大算法: 
      
        - BPTT
        - EKF
        - RTRL 
    
    - LSTM网络结构
    
    - GRU网络结构
    
    - 如何理解RNN

3. 受限玻尔兹曼机RBM
    
    - 玻尔兹曼机网络BM结构

    - 受限玻尔兹曼机网络RBM结构
 
    - 对照散度CD算法 
 
    - 深度信念网络DBN到深度玻尔兹曼机DBM

4. 自动编码器AE

    - 自动编码器结构与原理
    
    - 堆叠自动编码器Stack AE结构与原理

    - 稀疏自动编码器Sparse AE结构与原理

5. 对抗网络GAN

    - GAN结构与原理

    - GAN动物园

**第三部分**: 深度神经网络应用

1.	自然语言处理 

    - 词嵌入：Word2vec
    
    - 神经网络翻译：Seq2Seq 

2. 计算机图像视觉
    
    - 图像检测与分割

    - 常用算法
    
        - R-CNN
        - Fast R-CNN
        - Faster R-CNN
        - R-FCN
        - YOLO
        - SSD
        - YOLO2

**第四部分**: 深度神经网络实践

1. TensorFlow实例  

    - 案例(卷积神经网络): 手写数字识别 
	  
	  - 案例(无监督学习): 图片数据

2. NLP实例  
    
    - 案例(Word2vec): 基于词嵌入的文本分类
	  
	  - 案例(CNN): 基于CNN的文本分类



### 参考资料

---

## C-3. R语言编程与开发

**课程性质**: 大数据拓展系列

**大纲制定**: 汤银才

**课件开发**: 

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- R作为当今最流行的统计软件之一，具有非常多的优点，比如丰富的统计模型与数据处理工具，以及强大的可视化能力。但是最吸引R使用者的，莫过于从R USER到R DEVELOPER身份转变的过程。通过对R性能的研究，数据分析师可以通过R的性能监控与并行运算提升R程序的速度与精度，并且开发具有创新意义的R包。此外，R+多平台的联动以及R的应用开发也在当今的统计领域逐渐绽放出光彩。谁先掌握了这项技术，谁便可以捷足先登。

- 本课程通过编程篇、高性能计算、开发篇、基于shiny平台与基于R成熟应用介绍等五个板块，将细致讲述如何利用R语言进行高效编程与深度开发。

- 在R语言的基础之上，本课程能够帮助学员提高编程效率与程序性能，全面掌握R的并行计算与应用开发，从R的学习者转变为开发者。

### 课程目标:

本课程旨在培养学生/学员

- R语言编程进阶与初步R的开发

- 全方位掌握R的计算性能与实现并行计算

- 将R开发与业界相结合并进行应用设计


### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**：编程篇

1. R编程基础

    - R中的基本数据结构

    - R中的控制语句：if, for, while, repeat

    - 函数的构建与调用

    - 基本的debugging方法/函数

    - Scoping rules

2. R性能监控

    - 监控时间: system.time

    - 本地缓存工具memoise

    - 性能监控工具Rprof

    - summaryRprof

    - 性能可视化工具lineprof

**第二部分**： 高性能计算

1. 提升R的计算性能

    - R的缺陷与克服

    - 向量化编程/函数

    - apply系列函数：

        - apply
        - lapply
        - sapply
        - tapply
        - mapply

    - 其他Apply方式

2. 并行计算

    - 并行化介绍
    
        - 并行程序化目的与设计
        - Flynn并行计算分类(SISD,SIMD,MIMD)
        - 并行问题的分类: 
            
            a. embarrassingly-parallel
            b. Data-parallel
        
        - 并行化线程沟通协议(库): 
        
            a. PVM
            a. MPI
            a. NWS
            a. Socket
        
        - 并行场景:
            
            a. 多核心(CPU)
            a. 多计算机(Cluster)
            a. Grid计算
        
        - 常用的R并行计算包与4种协议下的速度比较
    - 常用并行R包

        - Rmpi: 基于MPI
        - snow (支持4种沟通协议)
        - snowfall (snow的简单化封装)
        - multicore (单计算机)
        - Parallel: multicore+snow (多计算机) 
            - apply类函数1
               (parApply,parLapply,parSapply)
            - apply类函数2
                (mclapply, mcmapply,需要fork进程支持)
        - nws(支持NWS-NetWorkSpace)
        - foreach: 代替apply系列函数, for
        - doMC: multicore+foreach (需要fork进程支持)
        - doParallel: multicore+foreach+snow
        - 案例1: K-means算法在平行实现
        - 案例2: 交叉验证

3. 其他并行问题        

    - 在Hadoop/Spark上分布式  

    - 并行MCMC介绍

    - cudaBayesreg：CUDA上贝叶斯分析

    - RScaLAPACK: 封装线性代数库ScaLAPACK

    - pRapply: lapply并行化

**第三部分**: 开发篇

1. R包开发

    - R包的构成
    - R包重新编译与安装
    - Rstudio中开发R包
    - 标准化R包开发流程
    - 案例: R语言天气可视化
    - 案例: 每日中国天气

2. R GUI开发

    - 早期开发平台: 
    
        - GWidgets
        - GTK/RGtk2
        - Tcl/Tk
        - Qt

    - 示例: 基于gWidgets和gWidgetsRGtk2计算软件开发

    - Rpanel

3. 基于HTMLWidgets应用与widget开发

    - HTMLWidgets介绍

    - 成熟的R Widget

    - Widget创建

4. 跨平台通信

    - Rserver与Java

    - Rsession与Java

    - rJava

    - Node.js与R

    - 案例: R中的BI实现
        - R + Tableau
        - R + PowerBI

**第四部分**: 基于shiny应用开发

1. shiny基础

    - shiny简介
    - 构建APP
    - 部件设计
    - 部署分享shinyapp

2. shiny高级开发
  
    - 高级shiny技巧
    - 开发案例

3. shinydashboard简介  

**第五部分**: 基于R成熟应用介绍

1. 统计分析平台

    - R commander
    - R Commander插件
    - R Deducer 

2. 数据挖掘平台 

    - Rattle  

3. R学习平台

    - swirl



### 参考资料

---

## C-4. 大数据平台技术与应用

**课程性质**: 大数据拓展系列

**大纲制定**: 汤银才

**课件开发**: 陈新宇，张东，练勇强

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- Apache Hadoop是一个开源的Java框架，用于处理和查询存放在大型商用硬件集群上的大量数据，成为行业对大数据处理的事实框架，具有四大特点：可扩展性、高性价比、灵活性和容错的解决方案。Apache Spark是一款开源的大数据分析平台，它立足于内存计算，从多迭代批量处理出发，兼顾数据仓库、流处理和图计算等多种计算范围，是大数据系统领域的全栈计算平台。Microsoft R Server是微软收购Revolution Aanlytics公司之后由Revolution R Enterprise打造的基于R的企业级大数据分析平台，通过利用和扩展开源R，可与开源R脚本、函数和CRAN软件包百分百兼容。支持各种大数据统计分析、预测性建模和机器学习功能，支持基于R的全套数据分析过程、探索、分析、可视化和建模等。

- 本课程通过五个模块介绍大数据分析常用的平台Hadoop和Spark和R的两个分布式扩展：微软R和supR, 学员可以系统地学到在这些平台上如何有效地进行分布式的数据存贮、数据管理、数据处理、统计分析和机器学习等函数、实际流程，并进行一些案例分析。

- 本课程是大数据分析的高级课程，旨在帮助学员掌握大数据分析平台和基于平台和扩展的R进行大数据分析的金钥匙。

### 课程目标:

本课程旨在培养学生/学员

- 了解大数据分析的常用的开源平台Hadoop和Spark 
- 掌握在Hadoop和Spark用R进行大数据分析

- 掌握R的扩展微软R Server/Client分析框架和开发中的supR的主要功能和函数


### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**: Hadoop

1. Linux操作基础

    - 大数据分析操作系统

    - Ubuntu安装

    - Linux下常用的命令

2. Hadoop基础

    - Hadoop介绍

    - hadoop集群搭建(centos/ubuntu/linux/mac)

    - HDFS原理

    - HDFS Shell操作实战

    - YARN介绍

3. Hadoop下的常用工具

    - Sqoop

        - Sqoop介绍与安装
        - Sqoop基础
        - Sqoop导入实战
        - Sqoop增量导入
        - Sqoop导出实战
        - Sqoop job

    - Hive

        - Hive架构
        - Hive环境搭建
        - Hive实战
        - Hive工作原理
        - 基于Hive的日志分析
        - 日志分析的ETL自动调度

    - HBase

        - HBase架构
        - HBase安装
        - HBase实战
        - Hive与HBase集成实战

    - kylin

        - kylin架构
        - kylin搭建
        - kylin实战
        - kylin性能调优

4. Rhadoop

**第二部分**: Spark基础

1. Spark入门

    - Map Reduce 思想介绍   

    - Spark简介
   
    - Spark运行架构
    
    - Spark工作原理
   
    - Ubuntu环境的准备
   
    - Spark集群搭建

2. Spark使用

   - Spark开发环境

   - 第一个Spark应用程序：WordCount

   - 在集群上运行Spark应用程序

   - Spark 监控管理

   - Spark 应用程序部署

   - Mapreduce和Spark模型的比较

**第三部分**: Spark提高

1. Spark SQL原理和实践

   - Spark SQL简介

   - Spark SQL 工具使用

   - Spark SQL实例与编程

   - DataFrame的创建

   - 读取和保存数据
      （读写Parquet、通过JDBC连接数据库、连接Hive读写数据）

2. Spark Streaming原理和实践    

    - Spark Streaming简介

    - Spark Streaming 流数据架构

    - Spark Streaming 原理与优化

    - DStream操作概述

        - 输入源
        - 转换操作
        - 输出操作

    - Storm 和Spark 的区别与比较

3. Spark MLlib实践

    - Spark MLlib简介与入门

    - 机器学习工作流

    - Spark MLlib 矩阵向量

    - Spark MLlib 回归与分类算法
         (逻辑斯蒂回归分类器、决策树分类器)

    - Spark MLlib 聚类算法
         (KMeans聚类算法、高斯混合模型(GMM)聚类算法)

    - Spark MLlib 关联规则算法

    - Spark MLlib 协同过滤推荐算法

    - Spark MLlib 特征抽取和处理

    - 案例：Spark 在线广告CTR 预测应用案例详解与分析

4. Spark 生态

    - Spark/Yarn 

    - Spark/Mesos

    - Spark/Zeppelin

5. SparkR

**第四部分**: 微软R Server简介

1. MRS介绍
    
    - 微软R三套件: Open, Client, Server
    
    - MRS/MRC的构成
    
    - MRS/MRC的优势
    
    - MRS/MRC处理大数据的架构: 
         
         - RevoScaleR
         - DistributedR
         - ConnectR

2. ScaleR数据的基本操作

    - 数据加载: rxImport

    - 数据存贮/转化为.xdf: rxImport

    - 查看.xdf的信息: rxXdfData, rxGetInfo
    
    - 改变变量类型:     
        
        - stringsAsFactors
        - colClasses
        - colInfo
    
    - 数据处理: rxDataStep
    
    - 数据可视化: rxHistogram, rxlinePlot

3. ScaleR统计分析

    - 描述性分析: rxSummary
    
    - 回归分析: rxLinMod 
    
    - logistic回归分析： rxLogit

    - 统计模拟

4. ScaleR机器学习
    
    - 聚类分析: K-Means
    
    - 分类算法: 
   
    - 异常值判断: rxOneClassSVM
   
    - 二分类/线性回归(SDCA): rxFastLiner
   
    - 二分类/回归
    
        - 决策树: rxFastTrees
        - 随机森林: rxFastForest
 
    - 二分类与多分类/回归
    
        - Logistic回归: rxlogisticRegression
        - 朴素贝叶斯：rxNeuralNet

**第五部分**:  SupR简介

-	SupR的设计理念

-	SupR的主要特性

-	SupR的安装

-	SupR的多线程计算

-	SupR的分布式实现 

### 参考资料

---

## C-5. Python机器学习

**课程性质**: 大数据拓展系列

**大纲制定**: 尹志

**课件开发**: 尹志，李浩

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 近两年来，数据分析师的岗位需求非常大，90%的岗位技能需要掌握Python作为数据分析工具，Python语言的易学性、快速开发，拥有丰富强大的扩展库和成熟的框架等特性很好地满足了数据分析师的职业技能要求。

- 本课程共五大模块，分别为Python基础语法，爬虫技术，数据挖掘与机器学习算法以及现代分析技术，让学员体验Python数据分析的强大功能，并能够解决实际案例。

- 本课程是大数据分析的高级课程，学员可以通过学习获得Python的高级用法，并能够理解应用机器学习算法解决实际问题。


### 课程目标:

本课程旨在培养学生/学员

- 熟悉数据分析的流程，包括数据采集、处理、可视化、数据建模等。

- 掌握Python语言作为数据分析工具，从而有能力驾驭不同领域数据分析实践。

- 快速积累多个业务领域数据分析项目经验，包括金融数据、文本数据及图像数据。

- 掌握使用Python实现基于机器学习及深度学习的数据分析和预测。

### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一部分**：python与机器学习概要

1. python编程与提高

    - 基本语法（条件/循环/函数/类/模块）

    - python语言编程的最佳实践经验

    - 最简单的制作python包的方法

    - 平台使用

2. 数据挖掘概览

    - 数据挖掘与模型

    - 建模流程和步骤

    - 常见算法

    - 高级应用案例解析

**第二部分**：机器学习初步 

1. 典型数据挖掘流程/示范

    - 基于titanic数据集预测生存概率

    - 演示如何进行绘图探索

    - 特征处理和建模

2. 降维与异常值处理

    -	PCA

    - LFA, LDA, ICA

    - RBM

    - 异常值判别

    - 正则化方法

    - 特征工程

**第三部分**：常用机器学习算法

1.	scikit-learn

2.	聚类: k-Means

3.	k-近邻

4.	二分类: 基于logistic回归

5.	朴素贝叶斯分类器

6.	感知机到SVM分类器

7.	感知机到ANN

8.	决策树

**第四部分**: 机器学习进阶

1. 机器学习进阶算法

    -	参数调优

    - 集成学习

    - 神经网络

    - 深度学习

2. 数据挖掘案例讲解

    -	基于MNIST数据集识别数字

    - 展示如何进行特征构造

    - 常规机器学习算法和深度学习算法的效果差异

    - 机器学习的结果评估

    - 深度学习的最新进展分享
    
3. 其他机器学习问题

    - 1.社交网络分析

    - 空间数据的展示与地理信息分析

    - 图像分析技术简介

**第五部分**：现代分析技术的应用

1.	文本挖掘(NLTK)

2.	社交网络分析(NLTK)

3.	空间数据的展示与地理信息分析

4.	图像分析技术简介


### 参考资料

---

# Series IV/实战系列

## D-1. 大数据统计分析实战训练营

**课程性质**: 大数据实战系列

**大纲制定**: 汤银才

**课件开发**: 

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

-  烧一道好菜，你需要三个要素：上好的食材，好用的炊具，以及好的烹饪方法。研究大数据也是同样的道理。想做好大数据的工作，你的食材是大数据，你的炊具是计算机，而最重要的烹饪方法则是统计思维。值得一提的是，食材和炊具只要肯花钱都可以买得到，唯有烹饪方法是你的——你必须自己学(林共进) 。统计学是数据分析的灵魂，是互联网+信息化时代大数据科学的核心。

- 本课程共8大模块，从数据分析师工具、收集与清洗数据、数据的探索性分析、数据建模预测与验证、数据相关性分析、回归分析与优化、复杂回归分析和时间序列分析等八个角度，对数据分析进行实战操作训练。

- 通过对本课程全流程数据分析的实训，学员可深刻地体会学好统计、用好统计、学以致用的重要性，以及解决实际问题过程中熟练掌握R/Python编程能力的必要性。

### 课程目标:

本课程旨在培养学生/学员

- 掌握统计分析和机器学习的常用技能

- 全面灵活地运用统计方法解决实际问题

- 将统计理论与实践完美结合


### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一讲**: 数据分析师工具

1. 数据处理的常规工具(数据库，软件，展示)

2. 训练营主要工具
  
    - R, RStudio
  
    - markdown, Rmarkdown
  
    - Python, jupyternotebook
  
    - git, GitHub

**第二讲**: 收集与清洗数据

1. 数据存贮系统

2. 寻找与获取来源的数据
  
    - 网络（web）
  
    - 社交网络(微信，博客)
  
    - API
  
    - 数据库(MySQL)

3. 数据清洗与处理

**第三讲**: 数据的探索性分析

1. 特征量的提取

2. 探索数据的分布

3. 探索数据之间的关系

4. 探索高维数据的信息

5. 数据的动态可视化

6. 探索数据的空间分布

**第四讲**: 数据的建模、预测与验证

1. 模型的类型

2. 预测流程

3. 交叉验证

4. 模型的评估

    - 回归模型评估

    - 分类模型评估
    
**第五讲**: 数据的相关性探索

1. 相关分析

    - 简单相关关系

    - 自相关分析

    - 偏相关分析

    - 互相关分析

    - 典型相关分析

2. 聚类分析

    - 关联分析
    
    - 关联规则挖掘
    
    - 序列模式挖掘

2. 主成分分析

**第六讲**: 数据的回归分析与优化

1. 简单线性回归

2. 多元线性回归

3. 回归模型的诊断

    - 残差分析

    - 变量选择

    - 模型比较 

    - 多重共线性

    - 离群值检测

4. 回归的改进: 正则化

5. Logistic回归

**第七讲**: 复杂回归分析

1. 梯度提升回归树

2. 神经网络

3. 支持向量机

4. 决策树

    - ID3算法

    - C4.5/5.0算法

    - CART算法

5. 集成算法   

**第八讲**: 时间序列分析

1. 时间序列概述
  
    - 时间序列的特征
  
    - 时间序列的描述性分析
  
    - 白噪声与平稳性

2. 平稳时间序列模型: ARMA模型

3. 非平稳序列模型：ARIMA模型

4. 异方差模型: GARCH类模型


### 参考资料

---

## D-2. 大数据分析师实战训练营(R)

**课程性质**: 大数据实战系列

**大纲制定**: 李舰

**课件开发**: 李舰，郞大为

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 近两年来，随着互联网+及数据贮存及计算能力的不断的提升，数据分析师的岗位需求越来越大。R与Python已经成为大数据时代各类数据分析两大主要语言或工具，成为继SAS之后21世纪数据分析师的新宠。R语言的易学性、强大的统计分析与可视化功能、丰富的R包和成熟的框架等特性很好地满足了许多数据分析师职业技能的要求。

- 大数据分析师是开发数据能源的主力军，他们不仅要分析、挖掘大数据所蕴藏的巨大价值，更要将其“提现转化”，为企业决策提供依据，让市场营销更精准无误。因此，熟练的掌握大数据分析技能尤为重要，分析师需要经验丰富的将理论与分析工具相结合，熟练灵活的解决各种业务问题。 

- 本课程共6大模块，从数据分析师工具、收集与清洗数据、数据的探索性分析、数据建模预测与验证、数据相关性分析、回归分析与优化、复杂回归分析和时间序列分析等八个角度，基于R对数据分析进行实战操作训练

- 本课程是大数据分析的实训课程，学员可以通过学习获得运用R进行数据分析以及数据挖掘的能力，学会基于进行数据挖掘和统计机器学习的各种技能，解决实际问题。

### 课程目标:

本课程旨在培养学生/学员

- 掌握统计分析技能

- 全面灵活的运用统计工具解决问题

- 将统计理论与实践完美结合


### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一讲**: 数据基础与R入门

  - 认识数据  

  - 数据分析方法概述

  - 大数据与数据科学概述

  - 常见分析工具概述

  - R漫谈

  - R工作环境介绍

  - Rstudio简介

  - R常用操作

  - R在业界应用案例分享

**第二讲**: R语言数据操作与编程基础

  - R基础数据结构

  - 函数操作与函数式编程

  - 数据的读入与写出

  - 文件的操作

  - R与数据库操作

  - 常用函数介绍(数据操作、字符处理、日期处理)

  - 编程与控制语句(条件、循环、apply操作)

  - dplyr与数据处理

  - 案例1：编写一个模拟排队的函数

  - 案例2：制作一个R包

  - 案例3：电商数据的清洗

  - 案例4：网站文本数据的清洗

**第三讲**: 统计建模

  - 线性回归与预测

  - 模型诊断

  - 回归扩展(非线性回归、logistic回归、lasso回归)

  - 主成分分析和因子分析

  - 聚类分析和判别分析

  - 多维变量的探索

  - 时间序列分析简介

  - 蒙特卡罗方法简介

  - 案例5：足球比赛数据分析

  - 案例6：销量数据的预测

**第四讲**: 数据挖掘与机器学习

  - 无监督学习介绍

  - 关联规则

  - 案例7：零售数据的关联规则挖掘

  - 分类算法: 从logistic回归说起

  - 案例8：信用卡违约预测分析

  - 机器学习结果评估

  - 多重交叉验证

  - 常用分类方法（决策树、随机森林、支持向量机）

  - 案例9：

  - 神经网络与深度学习

  - 案例10：足球比赛数据分析的机器学习    

**第五讲**: 数据可视化
  
  - 描述性统计与统计图形介绍

  - R中图形设备与作图方式

  - 常用图形参数介绍

  - ggplot2介绍

  - 动态可视化示例与业界进展

  - 数据分布的研究(直方图、QQ图、热图)

  - 数据关系的探索

      - 散点图与相关分析
      - 箱线图与因子分析
      - 马赛克图与列联表分析

  - 统计图应用案例及常见误区

  - 案例11：地理数据的可视化

  - shiny介绍

  - 案例12：使用shiny开发一个小型动态分析系统  

**第六讲**. 现代分析技术的应用

  - 自然语言处理与文本挖掘

  - 案例13：网络舆情的文本挖掘

  - 社交网络分析

  - 案例14：诗人的社会关系

  - 空间数据的展示与地理信息分析

  - 图像分析技术简介

  - 最优化方法与运筹学简介


### 参考资料

1. Curated Course， R－Data Analysis and Visualization-Five modules, PACKT, 2016.

---

## D-3. 大数据分析师实战训练营(python)

**课程性质**: 大数据实战系列

**大纲制定**: 尹志

**课件开发**: 尹志，李浩

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 近两年来，随着互联网+及数据贮存及计算能力的不断的提升，数据分析师的岗位需求越来越大。R与Python已经成为大数据时代各类数据分析两大主要语言或工具，成为继SAS之后21世纪数据分析师的新宠。Python语言的易学性、快速开发，拥有丰富强大的扩展库和成熟的框架等特性很好地满足了数据分析师职业技能的要求。

- 本课程共六大模块，不仅涉及Python基础语法、Python爬虫、文本挖掘，数据挖掘案例讲解以及现代分析技术，更侧重于基于Python的大数据分析、数据挖掘等实战方面课程的讲解，让学员体验Python数据分析的强大功能，并能够解决实际案例。

- 本课程是大数据分析的实训课程，学员可以通过学习获得运用Python进行数据分析以及数据挖掘的能力，学会基于Python进行数据挖掘和统计机器学习的各种技能，解决实际问题。

### 课程目标:

本课程旨在培养学生/学员

- 掌握Python的基础语法，并能够应用。

- 熟悉数据分析的整个流程及使用工具。

- 掌握Python爬虫、文本挖掘及数据挖掘等数据分析方法，并能够运用到实际案例中解决实际问题。


### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程介绍

**第一讲**： python基础

1. 数据分析方法概述及相关工具
      
    - 认识数据
  
    - 数据分析的步骤和原则（确定/分解/评估/决策）
  
    - 相关工具概述及对比（excel/spss/R/matlab/python/Java）

2.	python环境和基础语法

    - 安装anaconda套件

    - 基本数据结构（列表/字符串/字典）
    
    - 基本语法（条件/循环/函数/类/模块）
    
    - 基础环境linux-shell/IDLE/notebook
    
    - python与ipython
    
    - python语言编程的最佳实践经验
    
    - python在业界的典型应用

**第二讲**： 常用工具库

1.	基础工具库

    - 数值计算 numpy
    
    - 绘图与可视化 matplotlib与 Chart
    
    - 数据操作 pandas

    - 高级应用案例分享

2.	统计分析库
    
    - 概率和统计分析(statsmodels)
    
    - 科学计算和最优化(scipy)

    - 线性回归和logistic回归(statsmodels)

**第三讲**： python数据挖掘

1.	数据挖掘初步

    - 数据挖掘与模型
    
    - 建模流程和步骤
      
    - 常见数据挖掘算法
    
    - 特征工程
    
    - 正则化方法
    
    - 主成分分析(PCA)
    
    - 高级应用案例解析

2.	数据挖掘算法详解
      
    - 决策树
    
    - 集成学习
    
    - 参数调优
    
    - 感知机
    
    - 神经网络

    - 深度学习

**第四讲**：数据挖掘案例讲解

1.	titanic数据集

    - 绘图探索: 可视化
  
    - 特征处理和建模

    - 生存概率预测

2.	MNIST数据集: 数字识别
    
    - 特征构造
      
    - 常规机器学习算法和深度学习算法的效果差异
    - 机器学习的结果评估

    - 深度学习的最新进展分享

**第五讲**: python爬虫与文本挖掘

1.	Python爬虫

    - 数据采集（HTML解析，API使用）
    
    - 存储数据（MySQL）
    
    - 基础爬虫库（urllib，request）
    
    - 认识正则表达式（re模块）
    
    - 漂亮的爬虫库（BeautifulSoup）
    
    - 方便的现成框架(Scrapy)

2.	文本挖掘技术基础

    - 文本挖掘全流程概述

    - 自然语言处理库（NLTK）

    - TextBlob文本处理库介绍

    - 中文分词介绍（jieba）

    - 词云介绍(wordcloud)

3.	文本挖掘技术进阶

    - 文本挖掘预处理技术
    
    - 文本特征处理
  
    - 文本聚类
  
    - 主题模型
  
    - 基于深度学习的文本挖掘

    - 文本挖掘案例分享

**第六讲**：现代分析技术 

1.  社交网络分析 

2.  空间数据的展示与地理信息分析 

3.  图像分析技术简介



### 参考资料

---

## D-4. web全栈工程师数据可视化训练营

**课程性质**: 大数据实战系列

**大纲制定**: 周宁奕

**课件开发**: 周宁奕

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 在大数据时代，最为火爆的技术型岗位当属数据分析师(科学家)、算法工程师和全栈(前端)工程师。全栈(前端)工程师站在了时代的风口，他们既精通前端又能胜任后端(及移动端)，极大减少企业沟通成本。现在的调查分析表明，他们的就业趋向更好、需求更多，薪资也更胜一筹。现在web开发群体5成以上为全栈开发者，精通前后端的全栈工程师成了IT界新一代宠儿。然而其中懂得数据科学中数据动态可视化工程师成为大数据产业链中的稀缺人才。 

- 本课程由五大模板组成，逐步展示前后端web技术栈，通过对爬虫、数据库、数据清洗、可视化、部署上线等技术链路的技能学习和对地理可视化、graph可视化等专类可视化的实操经验积累，让学员学会在互联网+时代如何从容地获取数据、分析数据、通过动态可视化技术展示数据蕴含的价值。

- 本课程是大数据分析可视化实战训练营，学员将在课程案例中学习与体验，在随堂作业与结业项目中进行网站数据爬取、存储、可视化，全面复习并实践教授的技能，真正做到学以致用！


### 课程目标:

本课程旨在培养学生/学员

- 全面理解前后端web技术栈

-	全程学习爬虫、数据库、数据清洗、可视化、部署上线等技术链路

-	实操体验地理可视化、graph可视化等专门工具


### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一讲**: Web数据可视化概览

1. 可视化的纵与横

    -  数据可视化基础
    
    -  数据产业链路
    
    -  技术预备知识
        
        -  Nodejs
        -  HTML5基础
        -  SQL
    
    -  案例：
    
    -  基于地图的房价分析系统，mapbox
    
    -  基于图与文本搜索的邮件门分析工具，
             palantir与本拉登

2. 服务器与web基础
    
    -  web生态简介
    
    -  服务器的原理
    
    -  服务器简介与操作
  
    -  HTML5基础

**第二讲**: 爬虫与数据处理

1. Node.js爬虫技术

    - 如何获取数据，几种途径与特点

    - Node.js爬虫的基本原理、实现方法、应用方式
    - 实战（队列、请求池、模拟登录、ip代理）
    
    - 扩展与延伸
    
    - 案例：房价数据爬取

2. 关系型数据库PostgreSQL
    
    - 数据库选型
    
    - 导入数据、查询数据、更新数据、表结构与索引
    
    - SQL实战
    
    - 延伸: ORM、客户端与工具

    - 案例：
    
        - 上海房价分析
        - 上海轨道交通分析

**第三讲**：图表可视化

1. D3.js图表基础

    - 使用D3.js开发3种基础图表
    
    - 开发实时更新的动态基础图表
    
    - 作业：自身图表库的构建、基于Echarts的可视化、基于d3的通用图表可视化

2.	D3.js图表进阶

    - 延伸色彩的算法实现

**第四讲**: webGIS数据可视化

  - 地理数据可视化分类

  - 基于D3.js和leaflet的地理可视化

  - 用dat.gui实现参数控制

  - 更多延伸地理投影、色彩搭配

  - 案例：
  
      - 莆田黑医院可视化
        
      - 房价项目可视化

**第五讲**: 图可视化(graph layout)

  - 最简单的乒乓球游戏（JS/CSS动画）

  - 物理系统的横向扩展：
    
      - canvas
    
      - konva.js
    
      - 盗梦空间
    
      - 爱舍尔的画与脑洞打开的游戏扩展（双曲面空间与投影）

  - 物理引擎与图布局计算：
    
      - 泡泡图circle packing问题
  
      - 用Gephi优化图可视化算法

  - 基于D3.js实现力引导图可视化

  - 案例：
      
      - 希拉里邮件门分析
      - 社交网络分析插件


### 参考资料

---

## D-5. 量化金融分析师实战训练营

**课程性质**: 大数据实战系列

**大纲制定**: 张丹

**课件开发**: 彭志成，李浩，饶含悠

**建议学时**: 2/周 授课 + 1/周 操练，共54小时

### 课程介绍

- 在人工智能的浪潮下，各大顶级投行和金融机构纷纷转型和布局人工智能，优化金融管理与投资。因此，将专业的量化分析方法运用到到投资管理中，成为金融未来的发展方向之一，也是未来量化金融分析师的职业能力诉求。本课程旨在打造金融+计算机编程量化投资的综合复合型人才，在人工智能+大数据的大环境下，增加自身核心竞争能力，帮助你具备量化投资实战交易能力。

- 本课程共五大模块六个章节，分别从R语言基础和基于R角度
讲述量化投资策略、金融理论基础知识、投资理论模型，通过实战案例分析，模拟实操，让学员从实际操作中了解量化实盘交易的和交易系统设计。

- 本课程是量化分析师的专业基础课程，课程深入浅出介绍如何用R语言来实现量化投资的过程，数据抓取、平台建设、数据清洗、构建模型、回测、模拟交易、实盘交易全过程。 

### 课程目标:

本课程旨在培养学生/学员

- 能够使用R语言作为量化投资 
的主要工具，大幅提升培训人员动手能力 

- 掌握金融、编程和建模知识基础，拥有量化交易实盘操作能力

- 具备独立自主地研发新量化交易策略的能力

- 具备量化投资实战交易能力

### 适合学生/学员：

- 数学，统计学，应用数学，经济统计，数据科学与大数据技术，大数据技术与应用，......

### 课程大纲

**第一讲**：R语言基础

1.	R语言金融数据处理 

2.	金融数据结构和定义

3.	通过R语言获得金融数据 

4.	时间序列类型介绍

5.	金融数据处理

**第二讲**：金融理论入门 

1.	金融市场概要 

2.	资产的收益和风险刻度

3.	投资组合技术概要 

4.	技术分析在股票投资中的应用 

5.	量化投资技术和量化工具 

**第三讲**： 投资学理论模型 

1.	资本资产定价模型 

2.	套利定价理论

3.	多因子模型

4.	股利贴现模型 

**第四讲**： 金融市场入门 

1.	股票市场 

2.	国债、企业债、可转债 

3.	正回购，逆回购 

4.	基金、分级基金 

5.	指数

6.	期货 

**第五讲**： 实战案例 

1.	自回归模型

2.	均线模型 

3.	均值回归模型 

4.	追涨杀跌模型 

5.	配对交易模型

6.	多因子模型

**第六讲**： 量化投资系统构建

1.	数据采集

2.	数据平台

3.	回测系统

4.	会计系统

5.	交易系统

6.	数据可视化


### 参考资料

---
